
# Clippy Configuration
msrv = "1.88"

cognitive-complexity-threshold = 15
enum-variant-size-threshold = 256
enum-variant-name-threshold = 3
type-complexity-threshold = 250
too-many-lines-threshold = 500
too-many-arguments-threshold = 7

allow-expect-in-tests = true
allow-unwrap-in-tests = true
